version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: kingseafood_container
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env 

  redis:
    image: redis:latest
    container_name: redis-seafood
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PWD}  
      - REDIS_USER=${REDIS_NAME}     
    env_file:
      - .env 
volumes:
  redis-data:
