version: '3'

services:
  postgres:
    image: postgres:16
    ports:
      - 5436:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_USER=$USER
      - POSTGRES_DB=$DB_NAME